# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ffe0d318-966d-4f4d-a69e-60c24d40adb0";
      fsType = "btrfs";
      options = "noatime,ssd,autodefrag,compress=zlib,space_cache,degraded,recovery";
    };
  swapDevices =
    [ { device = "/dev/disk/by-label/PIXEL_SWAP"; } ];

  nix.maxJobs = 4;
}
